//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoenixConsulting.PaymentService.PayPal.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.sandbox.paypal.com/2.0/")]
        public string phoenixconsulting_PaymentService_PayPal_com_paypal_sandbox_www_PayPalAPIInterfaceService {
            get {
                return ((string)(this["phoenixconsulting_PaymentService_PayPal_com_paypal_sandbox_www_PayPalAPIInterface" +
                    "Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.sandbox.paypal.com/2.0/")]
        public string DomainTransformations_PaymentService_PayPal_com_paypal_sandbox_www_PayPalAPIInterfaceService {
            get {
                return ((string)(this["DomainTransformations_PaymentService_PayPal_com_paypal_sandbox_www_PayPalAPIInter" +
                    "faceService"]));
            }
        }
    }
}
